# Generated by Django 2.0.3 on 2018-03-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
